# Site settings
title: Welcome to OpenToAll
tagline: Homepage of OpenToAll, a friendly CTF team for both beginners and veterans.

# Social
socialimg: /img/social.jpg # be sure to change this image
facebook: fbusername
twitter: twusername
github: ghusername
googleplus: gusername
instagram: igusername


sass:
  style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
